4. Utilizando a biblioteca NumPy :
a. Cria um array de números 1 com shape (8, 2)
b. Cria um array de zeros com shape (5, 7)
c. Subtraia o novo array de outro com dados aleatórios e armazene o numa variável chamada subarray
d. Calcula a média dos valores do array subarray

Considerações:
Criar array de números 1 com 8 colunas e 2 linhas e respetivo print
Criar o array de zeros com 5 linhas e 7 colunas e respetivo print
Criar um array aleatório com 5 linhas e 7 colunas para subtrair ao array dos zeros e respetiva impressão
Os arrays vão dar o mesmo resultado
Por fim calcular a média

In [3]:
import numpy as np

# Array de números 1 com shape (8, 2)
array_uns = np.ones((8, 2))
print("Array de uns (8x2):")
print(array_uns)

# Array de zeros com shape (5, 7)
array_zeros = np.zeros((5, 7))
print("\nArray de zeros (5x7):")
print(array_zeros)

# Subtraçao do novo array de outro com dados aleatórios e armazenar numa variável chamada subarray
# Criando um array aleatório com shape (5, 7)
array_aleatorio = np.random.rand(5, 7)
subarray = array_aleatorio - array_zeros
print("\nArray aleatório (5x7):")
print(array_aleatorio)
print("\nSubarray (array aleatório - array de zeros):")
print(subarray)

# Calcular a média dos valores do array subarray
media_subarray = np.mean(subarray)
print(f"\nMédia dos valores do subarray: {media_subarray:.4f}")

Array de uns (8x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array de zeros (5x7):
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

Array aleatório (5x7):
[[0.83864896 0.89955503 0.53581042 0.29472073 0.75935347 0.54570562
  0.60818401]
 [0.54406797 0.99026959 0.60687278 0.35917107 0.553361   0.33031221
  0.52657385]
 [0.79993495 0.55940799 0.15000808 0.9438827  0.50889309 0.96486431
  0.23204944]
 [0.32096048 0.75563327 0.57112441 0.88022585 0.75949368 0.12158375
  0.20873042]
 [0.67100426 0.43408211 0.83919345 0.89142787 0.30874998 0.4866783
  0.23365993]]

Subarray (array aleatório - array de zeros):
[[0.83864896 0.89955503 0.53581042 0.29472073 0.75935347 0.54570562
  0.60818401]
 [0.54406797 0.99026959 0.60687278 0.35917107 0.553361   0.33031221
  0.52657385]
 [0.79993495 0.55940799 0.15000808 0.9438827  0.50889309 0.96486431
  0.23204944]
 [0.32096048 0.75563327 0.57112441 0.